name: "push event action"
description: "On push event build and publish AERIUS Java project, including running the unittests / a Sonar analysis"

inputs:
   GITHUB_TOKEN:
     required: true
     description: "Just pass the secrets.GITHUB_TOKEN to this action as input."
   SONAR_TOKEN:
     required: false
     description: "The token needed to push analyses to Sonar. If not set this will be skipped."
   NEXUS_USERNAME:
     required: true
     description: "The Nexus username needed to publish packages."
   NEXUS_PASSWORD:
     required: true
     description: "The Nexus password needed to publish packages."
   POM_PUBLISH_REPOSITORY_NAME:
     required: false
     description: "The repository as specified in the root POM to publish to."
     default: "aerius-nexus"
   ROOT_POM_DIRECTORY:
     required: false
     description: "The directory where the root POM can be found."
     default: "repo"
   JDK_VERSION:
     required: false
     description: "The version of the JDK to setup."
     default: 11

runs:
  using: "composite"
  steps:
    - uses: ./aerius-github-actions/common/checkout-java
      with:
        GITHUB_TOKEN: ${{ inputs.GITHUB_TOKEN }}
        JDK_VERSION: ${{ inputs.JDK_VERSION }}

    - uses: ./aerius-github-actions/common/cache-sonar-packages

    - uses: ./aerius-github-actions/common/cache-maven-packages

    - uses: ./aerius-github-actions/common/build-and-analyse-using-maven-and-sonar
      with:
        GITHUB_TOKEN: ${{ inputs.GITHUB_TOKEN }}
        SONAR_TOKEN: ${{ inputs.SONAR_TOKEN }}
        ROOT_POM_DIRECTORY: ${{ inputs.ROOT_POM_DIRECTORY }}

    - id: get-project-version
      uses: ./aerius-github-actions/common/get-maven-project-version
      with:
        ROOT_POM_DIRECTORY: ${{ inputs.ROOT_POM_DIRECTORY }}

    # Artifacts should only be published on pushes with a SNAPSHOT version
    - if: endsWith(steps.get-project-version.outputs.version, '-SNAPSHOT')
      uses: ./aerius-github-actions/common/publish-maven-artifacts
      with:
        NEXUS_USERNAME: ${{ inputs.NEXUS_USERNAME }}
        NEXUS_PASSWORD: ${{ inputs.NEXUS_PASSWORD }}
        POM_PUBLISH_REPOSITORY_NAME: ${{ inputs.POM_PUBLISH_REPOSITORY_NAME }}
        ROOT_POM_DIRECTORY: ${{ inputs.ROOT_POM_DIRECTORY }}

