name: "common :: Checkout Java"
description: "common :: Checkout repository and setup Java (JDK / Maven)"

inputs:
  JDK_VERSION:
    required: false
    description: "The version of the JDK to setup."
    default: 21
  POM_PUBLISH_REPOSITORY_NAME:
    required: false
    description: "The repository as specified in the root POM to publish to. Only needed for publishing."
    default: non-existent-server-id

runs:
  using: "composite"
  steps:
    - uses: ./aerius-github-actions/common/checkout

    - name: Setup Java (JDK / Maven)
      uses: actions/setup-java@03ad4de0992f5dab5e18fcb136590ce7c4a0ac95 # v5
      with:
        java-version: ${{ inputs.JDK_VERSION }}
        distribution: temurin
        cache: maven
        server-id: ${{ inputs.POM_PUBLISH_REPOSITORY_NAME }}
        server-username: NEXUS_USERNAME
        server-password: NEXUS_PASSWORD
