name: "pull_request event action"
description: "On pull_request event build AERIUS Java project, including running the unittests"

inputs:
  GITHUB_TOKEN:
    required: true
    description: "Just pass the secrets.GITHUB_TOKEN to this action as input."
  ROOT_POM_DIRECTORY:
    required: false
    description: "The directory where the root POM can be found."
    default: "repo"
  JDK_VERSION:
    required: false
    description: "The version of the JDK to setup."
    default: 17
  IGNORE_TEST_FAILURES:
    required: false
    description: "Allow tests to fail."
    default: false

runs:
  using: "composite"
  steps:
    - uses: ./aerius-github-actions/common/checkout-java
      with:
        GITHUB_TOKEN: ${{ inputs.GITHUB_TOKEN }}
        JDK_VERSION: ${{ inputs.JDK_VERSION }}

    - uses: ./aerius-github-actions/common/cache-maven-packages

    - uses: ./aerius-github-actions/common/build-using-maven
      with:
        GITHUB_TOKEN: ${{ inputs.GITHUB_TOKEN }}
        ROOT_POM_DIRECTORY: ${{ inputs.ROOT_POM_DIRECTORY }}
        IGNORE_TEST_FAILURES: ${{ inputs.IGNORE_TEST_FAILURES }}
