name: "pull_request event action"
description: "On pull_request event build AERIUS Java project, including running the unittests"

inputs:
  ROOT_POM_DIRECTORY:
    required: false
    description: "The directory where the root POM can be found."
    default: "repo"
  JDK_VERSION:
    required: false
    description: "The version of the JDK to setup."
  IGNORE_TEST_FAILURES:
    required: false
    description: "Allow tests to fail."
    default: false
  MAVEN_BUILD_PROFILE:
    required: false
    description: "The maven profile(s) to use when building. By default only 'all' will be used."
    default: "all"

runs:
  using: "composite"
  steps:
    - uses: ./aerius-github-actions/common/checkout-java
      with:
        JDK_VERSION: ${{ inputs.JDK_VERSION }}

    - uses: ./aerius-github-actions/common/build-using-maven
      with:
        ROOT_POM_DIRECTORY: ${{ inputs.ROOT_POM_DIRECTORY }}
        IGNORE_TEST_FAILURES: ${{ inputs.IGNORE_TEST_FAILURES }}
        MAVEN_BUILD_PROFILE: ${{ inputs.MAVEN_BUILD_PROFILE }}
