name: "Build Docker images for a generic AERIUS project"
description: "Build Docker images for a AERIUS project"

inputs:
  GITHUB_TOKEN:
    required: true
    description: "Just pass the secrets.GITHUB_TOKEN to this action as input."
  DOCKER_IMAGE_NAME:
    required: true
    description: "The Docker image name to use when building."
  DOCKER_WORK_DIRECTORY:
    required: false
    description: "The Docker work directory."
    default: "repo"
  DOCKERFILE_LOCATION:
    required: false
    description: "The location of the Dockerfile inside the Docker work directory."
    default: "Dockerfile"

runs:
  using: "composite"
  steps:
    - uses: ./aerius-github-actions/common/checkout
      with:
        GITHUB_TOKEN: ${{ inputs.GITHUB_TOKEN }}

    - name: Build Docker image
      uses: elgohr/Publish-Docker-Github-Action@v4
      with:
        name: ${{ inputs.DOCKER_IMAGE_NAME }}
        workdir: ${{ inputs.DOCKER_WORK_DIRECTORY }}/
        dockerfile: ${{ inputs.DOCKERFILE_LOCATION }}
        no_push: true

